language: c

matrix:
  include:
    - os: linux
      compiler: gcc
      env: TARGET=
    - os: linux
      compiler: gcc
      env: TARGET=debug
    - os: linux
      compiler: gcc
      env: TARGET=coverage
    - os: linux
      compiler: clang
      env: TARGET=
    - os: linux
      compiler: clang
      env: TARGET=debug
    - os: osx
      compiler: clang
      env: TARGET=
    - os: osx
      compiler: clang
      env: TARGET=debug

install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      brew update &&
      brew install libtermkey &&
      brew install lua &&
      luarocks install lpeg;
    fi

script:
  - id
  - env
  - locale
  - tty || true
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      ./configure && make $TARGET;
    else
      make local && make clean && make $TARGET;
    fi
  - file vis
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      otool -L vis;
    else
      ldd vis;
    fi
  - size vis
  - LD_LIBRARY_PATH="$(pwd)/dependency/install/usr/lib" ./vis -v
  - LD_LIBRARY_PATH="$(pwd)/dependency/install/usr/lib" make -C test/core
  - LD_LIBRARY_PATH="$(pwd)/dependency/install/usr/lib" make -C test/lua
  - LD_LIBRARY_PATH="$(pwd)/dependency/install/usr/lib" make -C test/vis
  - LD_LIBRARY_PATH="$(pwd)/dependency/install/usr/lib" make -C test/sam
  - LD_LIBRARY_PATH="$(pwd)/dependency/install/usr/lib" make -C test/vim

after_success:
  - if [ "$TARGET" = "coverage" ]; then
      bash <(curl -s https://codecov.io/bash);
    fi
