language: c

matrix:
  include:
    - os: linux
      compiler: gcc
      env: TARGET=
    - os: linux
      compiler: clang
      env: TARGET=
    - os: linux
      compiler: gcc
      env: TARGET=debug
    - os: linux
      compiler: clang
      env: TARGET=debug
    - os: linux
      compiler: gcc
      env: TARGET= CONFIG=--disable-lua
    - os: osx
      compiler: clang
      env: TARGET=
    - os: osx
      compiler: clang
      env: TARGET=debug
    - os: osx
      compiler: clang
      env: TARGET= CONFIG=--disable-lua
    - os: osx
      compiler: clang
      env: TARGET= CONFIG=--disable-tre

addons:
  apt:
    packages:
    - 9base
    - libacl1-dev

cache:
  directories:
    - $HOME/.cache/vis

before_install:
  - mkdir -p "$HOME/.cache/vis/sources" && mkdir dependency && ln -s "$HOME/.cache/vis/sources" dependency/sources

install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      brew update &&
      brew install libtermkey lua tre plan9port &&
      luarocks install lpeg;
    fi

script:
  - id
  - env
  - locale
  - tty || true
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      make local && make clean;
    fi
  - ./configure CFLAGS=-Idependency/install/usr/include LDFLAGS=-Ldependency/install/usr/lib $CONFIG
  - make $TARGET
  - file vis
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      otool -L vis;
    else
      ldd vis;
    fi
  - size vis
  - LD_LIBRARY_PATH="$(pwd)/dependency/install/usr/lib" ./vis -v
  - LD_LIBRARY_PATH="$(pwd)/dependency/install/usr/lib" make -C test/core coverage
  - LD_LIBRARY_PATH="$(pwd)/dependency/install/usr/lib" make -C test/lua
  - LD_LIBRARY_PATH="$(pwd)/dependency/install/usr/lib" make -C test/vis
  - LD_LIBRARY_PATH="$(pwd)/dependency/install/usr/lib" make -C test/sam
  - LD_LIBRARY_PATH="$(pwd)/dependency/install/usr/lib" make -C test/vim

after_success:
  - bash <(curl -s https://codecov.io/bash)
